var write = require('./')
var test = require('tape')
var read = require('./read')
var expected = require('./font.json')
var binFile = require('fs').readFileSync(__dirname+'/font-bin.fnt') 

// test('reads binary Buffer into BMFont object', function(t) {
//     var font = read(binFile)
//     t.deepEqual(font.common, expected.common, 'matches common')
//     t.deepEqual(font.info, expected.info, 'matches info')
//     t.equal(font.pages.length, expected.pages.length, 'matches pages')
//     t.deepEqual(font.chars, expected.chars, 'matches chars')
//     t.deepEqual(font.kernings, expected.kernings, 'matches kernings')
//     t.end()
// })

test('writes BMFont object to a binary Buffer', function(t) {
    var result = write(expected)
    var font = read(result)
    t.deepEqual(font.common, expected.common, 'matches common')
    t.deepEqual(font.info, expected.info, 'matches info')
    t.equal(font.pages.length, expected.pages.length, 'matches pages')
    t.deepEqual(font.chars, expected.chars, 'matches chars')
    t.deepEqual(font.kernings, expected.kernings, 'matches kernings')
    t.end()
})